### ISSUE TITLE
libvoikko is missing base forms

### ISSUE THREAD

**Issue by marta-lapina** [voikko/corevoikko#17]
I clone this repo and checked out "rel-libvoikko-3.7" edition. 
I'm working on CentOS 6.5:

I compiled it:
./autogen.sh
./configure --enable-vfst --prefix=/$HOME/vvfst --with-dictionary-path=$HOME/vvfst/voikkodict; make
su
make install

After the installation I tried:
$ echo alusta | voikkospell -m|grep BASEFORM

and didn't receive any output.

How can I fix this?

**Comment by marta-lapina** [comment]
I made voikkodict folder myself, downloaded the libraries and unzipped them there, following the instructions here: http://voikko.puimula.org/java.html

**Comment by marta-lapina** [comment]
This part of "make" is supposed to happen or is this a problem?

"copying selected object files to avoid basename conflicts...
libtool: link: ln setup/interface.o .libs/libvoikko.lax/lt1-interface.o || cp setup/interface.o .libs/libvoikko.lax/lt1-interface.o
ln: creating hard link .libs/libvoikko.lax/lt1-interface.o' =>setup/interface.o': Operation not permitted
libtool: link: ln hyphenator/interface.o .libs/libvoikko.lax/lt2-interface.o || cp hyphenator/interface.o .libs/libvoikko.lax/lt2-interface.o
ln: creating hard link .libs/libvoikko.lax/lt2-interface.o' =>hyphenator/interface.o': Operation not permitted
[and so on]"

I didn't notice anything else going wrong...

**Comment by hatapitk** [comment]
Your configure command suggests that you are trying to use VFST dictionary format. Did you intent to do that? It is an experimental feature; you should use latest master version from Github and build a dictionary yourself, those are not yet downloadable in precompiled form. If using VFST format is really what you want to do, please join libvoikko mailing list and tell us more about your use case so that we can help you forward.
If on the other hand you just wanted to have baseforms and are OK with the stable Malaga dictionary format please see issue #16. You probably did everything correctly but just downloaded a wrong dictionary, one that did not have the extra information containing stuff needed for morphological analysis.
I will close this as a question and not as a bug but feel free to ask help on the mailing list, I'm happy to help there.

**Comment by marta-lapina** [comment]
I wrote to mailing list, but haven't received a response yet. However, I have a detail to add to the question in the email: 

how do I get voikkovfstc to be compiled? 

"cat vvfst/all-sukija.att | sort -n | voikkovfstc -o vvfst/mor-sukija.vfst
/bin/sh: voikkovfstc: command not found"

**Comment by ahomansikka** [comment]
It seems you have compiled voikkovfstc but make does not find it.
You must put the directory where voikkovfstc is into your PATH.

**Comment by marta-lapina** [comment]
The problem is that it is really not-compiled. I couldn't find it among other voikko binaries:

[vagrant@localhost suomimalaga]$ ls -la ~/vvfst/bin/
total 392
drwxrwxr-x 2 vagrant vagrant   4096 Sep  4 11:00 .
drwxrwxr-x 6 vagrant vagrant   4096 Sep  4 09:44 ..
-rwxr-xr-x 1 vagrant vagrant  79711 Sep  4 11:00 voikkogc
-rwxr-xr-x 1 vagrant vagrant  68436 Sep  4 11:00 voikkohyphenate
-rwxr-xr-x 1 vagrant vagrant 239406 Sep  4 11:00 voikkospell

**Comment by ahomansikka** [comment]
./configure --help says that you need to add --enable-buildtools
to build voikkovfstc. Strange. I did not need that.

**Comment by marta-lapina** [comment]
That helped.

**Comment by hatapitk** [comment]
@marta-lapina: I haven't seen any mail from you on the mailing list. Looks like your problem might have already been solved but if not, please read the last paragraph from http://voikko.puimula.org/mail.html and re-send your mail. 
@ahomansikka: Building voikkovfstc has required --enable-buildtools since July 2013 to avoid having it accidentally distributed in unfinished state (we got a bug report from Debian about it). It might be that you still have an old version installed. Unweighted VFST format has not changed in a few years so it is entirely possible that an older version would still work for you.

**Comment by marta-lapina** [comment]
Yeah, the issue I was having is resolved.

**Comment by mthierydydu** [comment]
Tested at changeset `c682ff3` with 2.2 dictionaries from http://puimula.org/htp/testing/voikko-snapshot/:

I was also missing the base forms: using the **morpho** dictionary when instanciating `Voikko` worked for me: `new Voikko("fi-x-morpho", ...)`.
